#!/bin/bash
echo 24 > /sys/class/gpio/export || true
echo out > /sys/class/gpio/gpio24/direction
echo 1 >/sys/class/gpio/gpio24/value
sleep 1
echo 0 >/sys/class/gpio/gpio24/value

tr '\0' '\377' < /dev/zero | dd bs=1M count=4 of=image iflag=fullblock
dd if=${1} conv=notrunc of=image
flashrom -p linux_spi:dev=/dev/spidev0.0,spispeed=20000 -w image
echo 1 >/sys/class/gpio/gpio24/value
